# -*- coding: utf-8 -*-
"""Eksperimen_Ridwan_Widiyono.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bVoIg8sfgBAbTBKgQQWOQgYpCH9gy9hX

# **1. Perkenalan Dataset**

Tahap pertama, Anda harus mencari dan menggunakan dataset dengan ketentuan sebagai berikut:

1. **Sumber Dataset**:  
   Dataset diambil dari Kaggel dengan URl : https://www.kaggle.com/datasets/aliiihussain/netflix-movies-and-tv-shows-dataset

    **Deskripsi Dataset**: Dataset ini merupakan dataset Elite Syntetic Netflix Movies & TV Shows koleksi premium dan berkualitas tinggi yang terdiri dari 1.200 entri simulasi yang dimodelkan berdasarkan data platform streaming dunia nyata. Dataset ini menangkap struktur, gaya, dan keragaman katalog hiburan modern, sekaligus tetap aman, sintetis, dan sepenuhnya dapat disesuaikan.

# **2. Import Library**

Pada tahap ini, Anda perlu mengimpor beberapa pustaka (library) Python yang dibutuhkan untuk analisis data dan pembangunan model machine learning atau deep learning.
"""

#Type your code here
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""# **3. Memuat Dataset**

Pada tahap ini, Anda perlu memuat dataset ke dalam notebook. Jika dataset dalam format CSV, Anda bisa menggunakan pustaka pandas untuk membacanya. Pastikan untuk mengecek beberapa baris awal dataset untuk memahami strukturnya dan memastikan data telah dimuat dengan benar.

Jika dataset berada di Google Drive, pastikan Anda menghubungkan Google Drive ke Colab terlebih dahulu. Setelah dataset berhasil dimuat, langkah berikutnya adalah memeriksa kesesuaian data dan siap untuk dianalisis lebih lanjut.

Jika dataset berupa unstructured data, silakan sesuaikan dengan format seperti kelas Machine Learning Pengembangan atau Machine Learning Terapan
"""

#Type your code here
df = pd.read_csv("netflix_dataset.csv")
df.head()

"""# **4. Exploratory Data Analysis (EDA)**

Pada tahap ini, Anda akan melakukan **Exploratory Data Analysis (EDA)** untuk memahami karakteristik dataset.

Tujuan dari EDA adalah untuk memperoleh wawasan awal yang mendalam mengenai data dan menentukan langkah selanjutnya dalam analisis atau pemodelan.
"""

#Type your code here
df.shape

df.info()

df.describe()

df.isnull().sum()

df['description'].value_counts()

df['description'].value_counts().plot(kind='bar', figsize=(8,4))
plt.title("Distribusi Deskripi Film")
plt.show()

"""# **5. Data Preprocessing**

Pada tahap ini, data preprocessing adalah langkah penting untuk memastikan kualitas data sebelum digunakan dalam model machine learning.

Jika Anda menggunakan data teks, data mentah sering kali mengandung nilai kosong, duplikasi, atau rentang nilai yang tidak konsisten, yang dapat memengaruhi kinerja model. Oleh karena itu, proses ini bertujuan untuk membersihkan dan mempersiapkan data agar analisis berjalan optimal.

Berikut adalah tahapan-tahapan yang bisa dilakukan, tetapi **tidak terbatas** pada:
1. Menghapus atau Menangani Data Kosong (Missing Values)
2. Menghapus Data Duplikat
3. Normalisasi atau Standarisasi Fitur
4. Deteksi dan Penanganan Outlier
5. Encoding Data Kategorikal
6. Binning (Pengelompokan Data)

Cukup sesuaikan dengan karakteristik data yang kamu gunakan yah. Khususnya ketika kami menggunakan data tidak terstruktur.
"""

#piliih kolom yang dipakai
cols_used = [
    'show_id',
    'type',
    'title',
    'description',
    'release_year',
    'rating',
    'duration',
    'listed_in'
]

df_clean = df[cols_used]
df_clean.head()

#ubah nama kolom
df_clean = df_clean.rename(columns={
    'show_id': 'show_id',
    'title': 'menu_name',
    'description': 'description',
    'release_year': 'release_year',
    'rating': 'rating',
    'duration': 'duration',
    'listed_in': 'category'
})

df_clean.head()

df_clean.isnull().sum()

#agregasi per menu
df_menu = (
    df_clean
    .groupby(['category', 'type'])
    .agg(
        avg_release_year=('release_year', 'mean'),
        total_title=('show_id', 'count')
    )
    .reset_index()
)

df_menu.head()

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

num_cols = ['avg_release_year', 'total_title']

df_menu[num_cols] = scaler.fit_transform(
    df_menu[num_cols]
)

df_menu.head()

df_menu.to_csv(
    "netflixmovie_preprocessing.csv",
    index=False
)

